### ISSUE TITLE
bitcoind error

### ISSUE THREAD

**Issue by bitkarrot** [PLEBNET-PLAYGROUND/plebnet-playground-docker#115]
on commit f8d155a91b2233c5dc68b1f5e68e586120a29e78

while running containers, i see this error

playground-bitcoind  | 2022-05-31T04:38:15Z connect() to 23.45.205.250:38333 failed after wait: Connection refused (111)

**Comment by rsafier** [comment]
I'm guessing that was a peer at some point in the network, just couldn't connect to it. I show 48 peers with the seeding/mining node. 
Not seeing that specific one but similiar in logs:
``` 
2022-05-31T16:21:25Z Socks5() connect to oq6aasrewwgnzlyrfxttvlvedhbsqs4dubdeiszsv3cnrso7hmfhzwid.onion:38333 failed: host unreachable
```

**Comment by bitkarrot** [comment]
closing issue
