### ISSUE TITLE
Integrate LNC-Node into plebnet

### ISSUE THREAD

**Issue by bitkarrot** [PLEBNET-PLAYGROUND/plebnet-playground-docker#120]
I'm proposing that we integrate LNC into plebnet so that students can play around and develop their own LN enabled web applications on Node.js or React.

There is a web demo for connecting to LND node as a NPM package for node.js applications: 
https://github.com/lightninglabs/lnc-web

You can assign me to make a Docker container for the demo LNC web app.

What is LNC?

Lightning Node Connect (LNC) is a protocol that allows a node operator to safely and easily connect to a web or mobile application. LNC does not require the node to expose any ports. Instead, the application and the node are connected through a proxy server called the mailbox. The connection between node and application are end-to-end encrypted.

**Comment by rsafier** [comment]
LNC has looked cool, would be interesting to see if it actually works out of the box with custom signet. Haven't read docs fully not sure if we would have to provide a mailbox server to handle the traffic.

**Comment by bitkarrot** [comment]
there are two mail services i can think of that are useful for low volume mail and used in teaching. one is mailtrap.io and the other is sendgrid.com both can used on a free plan.

**Comment by bitkarrot** [comment]
i finally got around to looking at lnc-web. its not what i thought it was. i was looking for ln-service from https://github.com/alexbosworth/ln-service

if some pleb really is into this for self hosted nodes, then yes maybe it could be useful

**Comment by bitkarrot** [comment]
Closing this issue for now.
