### ISSUE TITLE
templating of docker-compose to allow user to select which parts they want to use

### ISSUE THREAD

**Issue by rsafier** [PLEBNET-PLAYGROUND/plebnet-playground-docker#18]

**Comment by rsafier** [comment]
can likely use simliiar scripting to what we are doing in clustering repo https://github.com/PLEBNET-PLAYGROUND/plebnet-playground-cluster/blob/master/plebnet_generate.py

**Comment by RandyMcMillan** [comment]
I just saw this repo...
Things making a bit more sense now...

**Comment by asherp** [comment]
#35 will address this issue.
