### ISSUE TITLE
docker-compose with c-lightning container?

### ISSUE THREAD

**Issue by npreti** [PLEBNET-PLAYGROUND/plebnet-playground-docker#75]
lnbook (https://github.com/lnbook/lnbook/blob/develop/04_node_client.asciidoc) has a c-lightning docker container that I was trying to see if it could be composed in the plebnet-playground environment to connect with existing lnd nodes over signet. Has anyone tried composing plebnet-playground with c-lightning instead of lnd?

**Comment by asherp** [comment]
starting a  [c-lighting](https://github.com/PLEBNET-PLAYGROUND/plebnet-playground-docker/tree/c-lightning) branch for this!

**Comment by rsafier** [comment]
yeah I had the container running, it just needed to be hooked up with the new yaml template setup, should make it easier to integrate now.  I had tested it back then, worked fine. Just all the tooling people have been working on has been LND so haven't spent much time on it.

**Comment by asher-pembroke** [comment]
I'm having problems linking the clightning container to bitcoind. Any ideas?

```sh
bitcoin-cli -rpcconnect playground-bitcoind -rpcport 38332 -rpcuser bitcoin -rpcpassword bitcoin
error: Could not connect to the server :8332 (error code 1 - "EOF reached")
```

**Comment by rsafier** [comment]
I know I had it running an synced up but might have been the clightning branch over in cluster repo. I know Randy also had it running for a short while

**Comment by asher-pembroke** [comment]
what's the status on this? Should i start a PR with my `c-lightning` branch or did @rsafier worked on this separately?

**Comment by rsafier** [comment]
let me go review that branch I can update image to what I found works well and you can get it integrated into the template.
